version: '3.8'

services:
  pg_container:
    image: postgres:14.1-alpine3.15
    container_name: pg_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-nannyvent}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data/initdb/:/docker-entrypoint-initdb.d/
      - ./backup:/var/lib/postgresql/backup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_nannyvent_network

  pgadmin_container:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - pg_container
    networks:
      - app_nannyvent_network

  my_flask_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_flask_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@pg_container:5432/${POSTGRES_DB:-nannyvent}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: ${FLASK_ENV:-production}
      DEBUG: ${DEBUG:-False}
    depends_on:
      - pg_container
    networks:
      - app_nannyvent_network

networks:
  app_nannyvent_network:
    driver: bridge

volumes:
  pg_data:
